# Generated by Django 5.1.8 on 2025-04-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='bed_type',
            field=models.CharField(choices=[('single', 'Single'), ('twin', 'Twin'), ('double', 'Double'), ('queen', 'Queen'), ('king', 'King')], default='single', max_length=20),
        ),
    ]
