# Generated by Django 5.2.3 on 2025-06-21 01:08

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='room_image')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.rooms')),
            ],
            options={
                'db_table': 'room_images',
            },
        ),
    ]
