# Generated by Django 5.2.3 on 2025-06-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
