# Generated by Django 5.1.8 on 2025-04-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rooms_bed_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='max_guests',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of guests allowed'),
        ),
    ]
