# Generated by Django 5.1.8 on 2025-04-15 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_rooms_max_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='capacity',
        ),
    ]
