# Generated by Django 5.1.8 on 2025-04-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
