# Generated by Django 5.1.8 on 2025-05-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
