# Generated by Django 5.1.8 on 2025-04-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0002_customusers_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='last_booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
