# Generated by Django 5.2.1 on 2025-05-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0002_customusers_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='phone_number',
        ),
    ]
