# Generated by Django 5.1.8 on 2025-04-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('no_show', 'No Show'), ('rejected', 'Rejected'), ('checkin_reminder', 'Checkin Reminder'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
