# Generated by Django 5.2.1 on 2025-05-10 08:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0003_remove_customusers_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customusers',
            name='valid_id',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='valid_id'),
        ),
    ]
