# Generated by Django 5.2.1 on 2025-05-10 09:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0004_customusers_is_verified_customusers_valid_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='valid_id',
        ),
        migrations.AddField(
            model_name='customusers',
            name='valid_id_back',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='valid_id_back'),
        ),
        migrations.AddField(
            model_name='customusers',
            name='valid_id_front',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='valid_id_front'),
        ),
    ]
