# Generated by Django 5.2.1 on 2025-05-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0005_remove_customusers_valid_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='valid_id_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('driver_license', "Driver's License"), ('national_id', 'National ID'), ('sss_id', 'SSS ID'), ('umid', 'Unified Multi-Purpose ID (UMID)'), ('philhealth_id', 'PhilHealth ID'), ('prc_id', 'PRC ID'), ('student_id', 'Student ID'), ('other', 'Other Government-Issued ID')], max_length=60, null=True),
        ),
    ]
