# Generated by Django 5.2.1 on 2025-05-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0008_alter_customusers_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='is_verified',
        ),
    ]
