# Generated by Django 5.2.1 on 2025-05-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0009_remove_customusers_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='is_verified',
            field=models.CharField(blank=True, choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified')], default='unverified', max_length=60, null=True),
        ),
    ]
