# Generated by Django 5.2.1 on 2025-05-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0012_customusers_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='valid_id_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
