# Generated by Django 5.2.3 on 2025-06-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'archived_users',
            },
        ),
    ]
