# Generated by Django 5.2.1 on 2025-06-14 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminDetails',
        ),
    ]
