# Generated by Django 5.1.8 on 2025-04-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='time_of_arrival',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
