# Generated by Django 5.1.8 on 2025-05-04 03:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='payment_method',
            field=models.CharField(choices=[('physical', 'Physical Payment'), ('gcash', 'GCash')], default='physical', max_length=20),
        ),
        migrations.AddField(
            model_name='bookings',
            name='payment_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='payment_proof'),
        ),
    ]
