# Generated by Django 5.1.8 on 2025-05-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookings_payment_date_bookings_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
