# Generated by Django 5.1.8 on 2025-05-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookings_down_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='payment_method',
            field=models.CharField(choices=[('physical', 'Physical Payment'), ('gcash', 'GCash')], default='gcash', max_length=20),
        ),
    ]
