# Generated by Django 5.2.1 on 2025-05-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_bookings_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='reservation',
        ),
        migrations.DeleteModel(
            name='Reservations',
        ),
    ]
