# Generated by Django 5.2.1 on 2025-05-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_transactions_reservation_delete_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='phone_number',
            field=models.CharField(default='09202129617', max_length=15),
            preserve_default=False,
        ),
    ]
