# Generated by Django 5.2.1 on 2025-05-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_bookings_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='valid_id',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone Number'),
        ),
    ]
